# Generated by Django 2.0.5 on 2018-05-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180514_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='access_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='house',
            name='desc',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='house',
            name='expiration_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='house',
            name='key_app_eco_bee',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='house',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
